### ISSUE TITLE
Adding API key to sample.yml but still get token error

### ISSUE THREAD

**Issue by tdoga** [mattyjones/wraith#122]
Hello,
i add my api key to sample.yml but still i get error when i run the script. ( token error )

pwd > wraith/config/sample.yml

What should i do ?

**Comment by VikzSharma** [comment]
same here man very irritating

**Comment by leorac** [comment]
@dogagelisli documentation says

```
Copy config/sample.yml or the below configuration to ~/.wraith/config.yml. This will allow you to get up and running for basic scans without having to figure out the flags. Any of these values can be overwritten on the commnd line as well. You will need to generate your own api tokens for github and gitlab if you are scanning against them.
```

So you need to copy the file to the right path. But even doing so, the github token don't look to be recognized. Anyone has figured it out?

**Comment by mattyjones** [comment]
@dogagelisli @VikzSharma 

I am not sure of the issue but the following works on my test box
- MacOS 12.4
- Apple M1
- 24" iMac (2021)

I download the **0.0.9** release and built it using `make build` then I executed `bin/wraith-darwin scanGithub` with no flags and a clean `env`. With these steps I was able to clone and scan both private and public repos for orgs I am in and orgs I am not in.

The config file is located at `/Users/bob/.wraith/config.yaml`

The config file used is
```yaml
---
commit-depth: -1
debug: false
github-api-token: not_a_real_token_and_dont_want_to_trip_github_scanning
github-orgs:
  #    - ansible
    - N0MoreSecr3ts
github-repos:
  #    - ansible
      #github-users:
      #- <user 1>
      #gitlab-api-token: <token>
      #gitlab-targets:
      #- <repo 1>
      #- <project 1>
      #- <user 1>
scan-forks: false
scan-tests: false
ignore-extension:
    - .html
    - .css
    - .log
ignore-path:
    - static/
    - docs/
    - .idea/
in-mem-clone: false
  #local-paths:
  #    - ../relative/path/to/file.md
  #    - $HOME/path/to/file.pl
  #    - /absolute/path/to/file.rb
confidence-level: 3
num-threads: 1
  #local-repos:
  #    - ../wraith
  #    - /home/bob/Go/src/foo
silent: false
web-server: true
json: false
csv: false
test-signatures: false
signatures-path: "~/.wraith/signatures"
signature-file:
    - ../wraith-signatures/signatures/default.yaml
signatures-url: "https://github.com/N0MoreSecr3ts/wraith-signatures"
signatures-version: "0.2.0"
```
